# Usa a imagem oficial nginx:stable-alpine como base
FROM nginx:stable-alpine

# Removendo o arquivo de configuração padrão para evitar conflitos
RUN rm -f /etc/nginx/conf.d/default.conf

# CORREÇÃO: Usando o nome da pasta que você informou (nginx-config.d)
COPY nginx-config.d /etc/nginx/conf.d

RUN rm /var/log/nginx/access.log && \
    rm /var/log/nginx/error.log  

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
